### ISSUE TITLE
Appstream metadata license is invalid

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/io.github.cloose.CuteMarkEd#6]
GPL2.0+ is not a valid appstream license according to appstream-glib.

Waiting on @Alexander-Wilms to confirm a change of license.

This was noticed and skipped over in #5 as to accelerate merger.

**Comment by Alexander-Wilms** [comment]
GPL-2.0-or-later is alright

**Comment by lionirdeadman** [comment]
It's not. Look at the Appstream specification : https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license

You can also try to validate it yourself using appstream-glib, it doesn't pass validation. @Alexander-Wilms
